[package]
name = "udp_smart_devices"
version = "0.1.0"
edition = "2021"

[dependencies]
smart_devices = { path = "../smart_devices" }
tokio = { version = "1.42.0", features = [
    "net",
    "io-util",
    "rt",
    "rt-multi-thread",
    "macros",
    "sync",
    "time",
] }
