[package]
name = "tcp_smart_devices"
version = "0.1.0"
edition = "2021"

[dependencies]
smart_devices = { path = "../smart_devices" }
stp = { path = "../stp" }
tokio = { version = "1.42.0", features = [
    "net",
    "io-util",
    "rt",
    "macros",
    "sync",
] }
